name: Deploy Flatpak

on:
  workflow_call:
    inputs:
      manifestPath:
        required: true
        type: string
    secrets:
      managerToken:
        required: true

jobs:
  flatpak:
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    name: "Flatpak"
    runs-on: ${{ matrix.arch == 'aarch64' && 'ARM64' || 'ubuntu-latest' }}
    container:
      image: ghcr.io/tau-os/builder:nightly
      options: --privileged
    steps:
    - uses: actions/checkout@v3
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
      name: "Build"
      with:
        manifest-path: ${{ inputs.manifestPath }}
        cache-key: flatpak-builder-${{ github.sha }}-${{ matrix.arch }}
        repository-name: catalogue
        repository-url: https://fyralabs.com/catalogue.flatpakrepo
        arch: ${{ matrix.arch }}
    - uses: flatpak/flatpak-github-actions/flat-manager@v6.1
      name: "Deploy"
      with:
        repository: stable
        flat-manager-url: https://manager.flatpak.fyralabs.com
        token: ${{ secrets.managerToken }}
