name: Upload RPM

on:
  workflow_call:
    inputs:
      tauOSVersion:
        required: true
        type: string
      name:
        required: true
        type: string
      buildVariant:
        default: noarch
        type: string
    secrets:
      repoKnownHosts:
        required: true
      repoPrivateKey:
        required: true
      repoIP:
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4.1.7
        with:
          name: ${{ inputs.name }}-${{ inputs.buildVariant }}-signed
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.repoPrivateKey }}
          known_hosts: ${{ secrets.repoKnownHosts }}
      - run: ssh repo@${{ secrets.repoIP }} "mkdir -p /var/www/repo.tauos.co/releases/${{ inputs.tauOSVersion }}/"
      - run: shopt -s globstar && scp **/*.rpm repo@${{ secrets.repoIP }}:/var/www/repo.tauos.co/releases/${{ inputs.tauOSVersion }}/
      - run: ssh repo@${{ secrets.repoIP }} "createrepo --update /var/www/repo.tauos.co/releases/${{ inputs.tauOSVersion }}/"
      - run: ssh repo@${{ secrets.repoIP }} "rm -f /var/www/repo.tauos.co/releases/${{ inputs.tauOSVersion }}/repodata/repomd.xml.asc && gpg --output /var/www/repo.tauos.co/releases/${{ inputs.tauOSVersion }}/repodata/repomd.xml.asc -u tauOS --no-tty --detach-sign --armor /var/www/repo.tauos.co/releases/${{ inputs.tauOSVersion }}/repodata/repomd.xml"
